# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-11 06:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=30)),
                ('semester', models.CharField(max_length=30)),
                ('subjectname', models.CharField(max_length=30)),
                ('studentname', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=30)),
                ('coursename', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='course',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('department', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('ctype', models.CharField(default='type1', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departmentname', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='marks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departmentname', models.CharField(max_length=30)),
                ('coursename', models.CharField(max_length=30)),
                ('semester', models.CharField(max_length=30)),
                ('studentname', models.CharField(max_length=30)),
                ('s1', models.CharField(max_length=30)),
                ('s2', models.CharField(max_length=30)),
                ('s3', models.CharField(max_length=30)),
                ('s4', models.CharField(max_length=30)),
                ('s5', models.CharField(max_length=30)),
                ('S6', models.CharField(max_length=30)),
                ('S7', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=30)),
                ('std_name', models.CharField(max_length=30)),
                ('deptname', models.CharField(max_length=30)),
                ('semester', models.CharField(max_length=30)),
                ('joindate', models.CharField(max_length=30)),
                ('admno', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
                ('contactno', models.CharField(max_length=30)),
                ('emailid', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semname', models.CharField(max_length=30)),
                ('coursename', models.CharField(max_length=30)),
                ('departmentname', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departmentname', models.CharField(max_length=30)),
                ('subjectname', models.CharField(max_length=30)),
                ('coursename', models.CharField(max_length=30)),
                ('semester', models.CharField(max_length=30)),
            ],
        ),
    ]
