# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-09-11 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_auto_20180911_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='subjectname2',
            field=models.CharField(default='', max_length=30),
        ),
    ]
