# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-09-11 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_attendance_subjectname2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='subjectname3',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='subjectname4',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
