# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-09-11 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0008_auto_20180911_1256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='subjectname',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='studentname',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
