# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-09-12 05:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0009_auto_20180911_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='studentname',
            field=models.CharField(max_length=30),
        ),
    ]
