# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-09-12 06:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0010_auto_20180912_0506'),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parentname', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=30)),
                ('std_name', models.CharField(max_length=30)),
                ('deptname', models.CharField(max_length=30)),
                ('semester', models.CharField(max_length=30)),
                ('joindate', models.CharField(max_length=30)),
                ('admno', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
                ('contactno', models.CharField(max_length=30)),
                ('emailid', models.CharField(max_length=30)),
                ('username', models.CharField(default='user', max_length=30)),
                ('password', models.CharField(default='pass', max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='parent',
        ),
    ]
