# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-09-12 06:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0011_auto_20180912_0624'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='coursename',
            field=models.CharField(default='', max_length=30),
        ),
    ]
