# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-09-12 06:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0012_student_coursename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marks',
            name='S6',
        ),
        migrations.RemoveField(
            model_name='marks',
            name='S7',
        ),
        migrations.RemoveField(
            model_name='marks',
            name='s1',
        ),
        migrations.RemoveField(
            model_name='marks',
            name='s2',
        ),
        migrations.RemoveField(
            model_name='marks',
            name='s3',
        ),
        migrations.RemoveField(
            model_name='marks',
            name='s4',
        ),
        migrations.RemoveField(
            model_name='marks',
            name='s5',
        ),
        migrations.AddField(
            model_name='marks',
            name='final',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='marks',
            name='internal1',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='marks',
            name='internal2',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='marks',
            name='internal3',
            field=models.CharField(default='', max_length=30),
        ),
    ]
