# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-09-12 06:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0013_auto_20180912_0639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='final',
            field=models.CharField(default='NA', max_length=30),
        ),
        migrations.AlterField(
            model_name='marks',
            name='internal1',
            field=models.CharField(default='NA', max_length=30),
        ),
        migrations.AlterField(
            model_name='marks',
            name='internal2',
            field=models.CharField(default='NA', max_length=30),
        ),
        migrations.AlterField(
            model_name='marks',
            name='internal3',
            field=models.CharField(default='NA', max_length=30),
        ),
    ]
