# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-09-12 07:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0014_auto_20180912_0643'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marks',
            old_name='final',
            new_name='avmarks',
        ),
        migrations.RenameField(
            model_name='marks',
            old_name='internal1',
            new_name='examname',
        ),
        migrations.RenameField(
            model_name='marks',
            old_name='internal2',
            new_name='remarks',
        ),
        migrations.RemoveField(
            model_name='marks',
            name='internal3',
        ),
    ]
