# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-09-13 05:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0015_auto_20180912_0722'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='avattendance',
            field=models.IntegerField(default=0),
        ),
    ]
