# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-09-13 07:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0016_attendance_avattendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(max_length=30)),
                ('date', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
