# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-09-26 05:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0017_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='fee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.CharField(max_length=30)),
                ('fee', models.CharField(default='0', max_length=30)),
            ],
        ),
    ]
