# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-09-26 06:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0024_auto_20180926_0628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='file',
            field=models.FileField(upload_to='files/'),
        ),
    ]
