# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-09-26 07:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0031_auto_20180926_0650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='desc',
            field=models.CharField(max_length=100),
        ),
    ]
